"""leave_application

Revision ID: 800c19a62d8c
Revises: cd8f3f10f609
Create Date: 2024-08-12 05:12:29.403013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800c19a62d8c'
down_revision = 'cd8f3f10f609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('leave_start_date', sa.String(), nullable=False),
    sa.Column('leave_end_date', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leave_application')
    # ### end Alembic commands ###
